# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: [Monal Narasimhamurthy](https://www.google.com/search?rlz=1C5CHFA_enUS818US818&ei=mAUxXeDPIYat_QahnqOwBg&q=pronounce+monal&oq=pronounce+monal&gs_l=psy-ab.3..0i7i30l2j0i30j0i5i30l2j0i8i30.52173.52173..52474...0.0..0.67.67.1......0....1..gws-wiz.......0i71.itioAjnZdZY&ved=0ahUKEwjg-4ud1L_jAhWGVt8KHSHPCGYQ4dUDCAo&uact=5)
email: monal.narasimhamurthy@gmail.com
description: Graduate Student, University of Colorado Boulder
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://monal.github.io" # the base hostname & protocol for your site
github_username:  monal

# Build settings
markdown: kramdown
