# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monal Narasimhamurthy
email: monal.narasimhamurthy@colorado.edu
description: Graduate Student, University of Colorado Boulder
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "http://monal.github.io" # the base hostname & protocol for your site
github_username:  "monal"
linkedin_username: "monal-narasimhamurthy"
js: false

# Build settings
markdown: kramdown
